//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ultimate_Tech_Premio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chamado
    {
        public int Id { get; set; }
        public string nome_usuario { get; set; }
        public Nullable<System.DateTime> data_chamado { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public string status { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> nota_avaliacao { get; set; }
        public Nullable<int> habilidade_avaliacao { get; set; }
        public Nullable<int> cordialidade_avaliacao { get; set; }
        public string sugestao_avaliacao { get; set; }
        public string solucionado_avaliacao { get; set; }
        public Nullable<bool> avaliado { get; set; }
        public string retorno_tec { get; set; }
        public Nullable<int> Tecnico1 { get; set; }
        public Nullable<bool> reaberto { get; set; }
        public string motivo_reaberto { get; set; }
        public Nullable<int> solucionado_nota { get; set; }
        public string Tecnico_nome { get; set; }
        public Nullable<bool> Em_Andamento { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
